title: EUROPE-IGM-ATLAS
page-top-title: EUROPE-IGM-ATLAS
top-section-bg-text: The European Atlas of Spatially Disaggregated Intergenerational Mobility
copyright-text: '&copy; Sarah McNamara, Guido Neidhöfer, and Patrick Lehnert. 2026. All Rights Reserved.'
